### ISSUE TITLE
Possible deprecation

### ISSUE THREAD

**Issue by dungducphan** [davidchall/homebrew-hep#132]
### Possible deprecation

- I ran `brew install herwig++` and some dependency installations showed these warnings:

```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/rivet.rb:64:in `caveats'
Please report this to the davidchall/hep tap!

...

Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/davidchall/homebrew-hep/Formula/lhapdf.rb:49:in `caveats'
Please report this to the davidchall/hep tap!

```

**Comment by ebothmann** [comment]
This issue has been addressed by #146. Thanks for flagging this!
